services:
  consul:
    container_name: consul-server
    image: hashicorp/consul:latest
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - consul_data:/consul/data 
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    restart: always
    command: consul agent -server -data-dir=/consul/data  -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
volumes:
  consul_data:
    name: consul_data