services:
  consul-server:
    container_name: consul-server
    image: hashicorp/consul:latest
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - consul_data:/consul/data 
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    restart: always
    networks:
      - consul
    command: consul agent -server -data-dir=/consul/data  -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0

  consul-client:
    container_name: consul-client
    image: hashicorp/consul:latest
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    restart: always
    command: consul agent -data-dir=/consul/data -node=client-1 -join=consul-server
    depends_on:
      - consul-server
    volumes:
      - consul_client_data:/consul/data
    
volumes:
  consul_data:
    name: consul_data
  consul_client_data:
    name: consul_client_data

networks:
  consul:
    name: consul
    driver: bridge